version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    restart: always
    ports:
      - "8351:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongodb_network

networks:
  mongodb_network:

volumes:
  mongodb_data:
    driver: local
